[package]
name = "next_rs_traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.60"
sycamore = {version = "0.8.2", features = ["ssr"]}
